*Docker compose.yml *

sudo docker run -d --name=redis redis

sudo docker run -d --name=db postgres:9.4

sudo docker run -d --name=vote -p 5000:80 --link redis:redis voting-app

sudo docker run -d --name=result -p  5001:80 --link db:db resalt-app

docker run -d --name=worker --link db:db --link redis:redis worker

sudo docker-compose up -d
sudo docker-compose down
sudo aa-remove-unknown

=docker-compose.yml=

redis:
   image: redis
db:
   image: postgres:9.4

vote:
  image: voting-app
  ports:
    - 5000:80
  links:
   - redis

result:
  image: result-app
  ports:
   - 5001:80
  links:
  - db

worker:
  image: worker
  links:
     - redis
     - db

==========

version: '3'
networks:
   batman:
     driver: bridge

services:
  os:
    image: "ubuntu"
    ports:
      - "80:80"
    networks:
      - batman

===============
version: '3.3'

services:
   db:
       image: mysql:5.7
       volume:
           - db_data:/var/lib/mysql
        restart: always
        environment:
           MYSQL_ROOT_PASSWORD: admin1234
           MYSQL_DATABASE:  wordperss
           MYSQL_USER: wordpress
           MYSQL_PASSWORD: wordpress
 
     wordpress:
          depends_on:
             - db
           image: wordpress:latest
           porsts:
               - "8000:80"
           restart: always
           environment:
             WORDPRESS_DB_HOST: db:3306
             WORDPRESS_DB_USER: wordpress
             WORDPRESS_DB_PASSWORD: wordpress
              WORDPRESS_DB_NAME: wordpress
volume:
    db_data {}