-- DB_DQ_IMPROV_RV_1200."PUBLIC".DEMO_CUSTOMERS definition

create or replace TABLE DB_DQ_IMPROV_RV_1200.PUBLIC.DEMO_CUSTOMERS (
	ID NUMBER(38,0),
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	GENDER VARCHAR(50),
	AGE VARCHAR(50),
	OCCUPATION VARCHAR(50),
	MARITALSTATUS_OUT VARCHAR(50),
	SALARY_OUT VARCHAR(50),
	ADDRESS VARCHAR(50),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	ZIP VARCHAR(50),
	PHONE VARCHAR(50),
	ALT_PHONE VARCHAR(50),
	EMAIL VARCHAR(50),
	SUBDATE VARCHAR(50),
	NUMBER_OF_RENTALS NUMBER(38,0)
);